# Lab 7: LSH

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
import time
def time_execution(code):
    start = time.perf_counter()
    result = eval(code)
    run_time = time.perf_counter() - start
    return run_time, result

## Load Images

In [3]:
imgs = []
for i in range(1, 41):
    filename = "{}.jpg".format(i)
    img_bgr = cv2.imread('dataset/{}'.format(filename))
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    imgs.append(img_rgb.copy())

target_bgr = cv2.imread('target.jpg')
target = cv2.cvtColor(target_bgr, cv2.COLOR_BGR2RGB)

## Feature Extracting

In [4]:
import features

img_features = []
for img in imgs:
    feature = features.extract(img)
    img_features.append(feature)
    print(feature)

[2 2 0 2 2 0 2 2 0 2 2 0]
[1 1 0 1 1 0 1 2 0 1 1 1]
[2 2 0 2 1 0 2 2 0 2 1 0]
[2 2 0 1 2 0 1 1 1 0 1 2]
[1 1 1 2 1 0 2 1 0 2 1 0]
[1 2 0 2 2 0 2 2 0 2 2 0]
[1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 2 1 0 1 1 0 2 1 0]
[2 2 0 2 2 0 2 2 0 2 2 0]
[2 1 0 2 1 0 2 1 0 2 1 0]
[0 2 2 0 2 2 0 2 2 0 2 2]
[0 0 2 2 1 0 0 0 2 2 1 0]
[0 1 2 0 1 2 0 2 1 0 2 2]
[2 0 0 2 0 0 2 0 0 2 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1]
[2 0 0 2 0 0 2 0 0 2 0 0]
[0 1 2 0 1 2 0 1 2 0 1 2]
[1 1 0 2 1 0 2 2 0 2 1 0]
[1 2 0 1 2 0 1 2 0 1 2 0]
[2 2 0 2 1 0 2 1 0 2 1 0]
[2 1 1 2 1 0 2 1 1 2 1 0]
[2 1 0 2 0 0 2 0 0 2 0 0]
[0 0 2 1 1 2 0 0 2 0 0 2]
[1 1 1 1 1 0 2 2 0 1 1 1]
[1 1 1 2 0 0 1 1 1 2 0 0]
[0 1 2 0 1 1 0 0 2 1 1 1]
[2 0 0 2 0 0 2 0 0 2 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1]
[1 1 1 1 1 1 2 1 0 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1]
[2 0 2 1 0 2 2 0 1 2 0 1]
[1 1 1 1 1 1 1 1 0 1 1 1]
[2 2 0 2 1 0 2 1 0 2 0 0]
[1 2 0 1 2 0 0 2 0 1 2 0]
[2 0 0 2 0 0 2 0 0 2 0 0]
[0 0 2 0 0 2 0 0 2 0 0 2]
[0 1 2 0 1 2 0 2 2 0 1 2]
[0 1 2 2 1 0 0 1 2 2 1 0]
[1 1 0 2 0 0

## Image Matching using LSH

In [5]:
import lsh

table = lsh.LSHashTable(4, 12, 6)
for i, feature in enumerate(img_features):
    table.insert(feature, i + 1)

In [6]:
target_feature = features.extract(target)
run_time, result = time_execution("table.search(target_feature)")
print("result: {}, time: {}".format(result, run_time))

result: 38, time: 0.00021160199958103476


## Image Matching using KNN

In [7]:
train_data = np.array(img_features, dtype='float32')
labels = np.array(range(1, 41), dtype='float32')
target_feature = np.array([features.extract(target)], dtype='float32')

In [8]:
knn = cv2.ml.KNearest_create()
knn.train(train_data, cv2.ml.ROW_SAMPLE, labels)
run_time, result = time_execution("knn.findNearest(target_feature, 1)")
print("result: {}, time: {}".format(int(result[1][0][0]), run_time))

result: 38, time: 0.00012410100043780403


## LSH with SIFT

In [9]:
import sift_features

img_features = []
for img in imgs:
    feature = sift_features.extract(img)
    img_features.append(feature)

In [10]:
table = lsh.LSHashTable(16, 128, 16)
for i, feature in enumerate(img_features):
    table.insert(feature, i + 1)

In [11]:
target_feature = sift_features.extract(target)
run_time, result = time_execution("table.search(target_feature)")
print("result: {}, time: {}".format(result, run_time))

result: 38, time: 0.005075263999970048
